#!/bin/bash

# Load the Kubeconfig generated by start_kubeflow.py
export KUBECONFIG=~/.kube/config_k3s_custom

echo "Using KUBECONFIG=$KUBECONFIG"

# Clean up previous job
echo "Deleting old job (if exists)..."
kubectl delete -f kubeflow_test_job.yaml 2>/dev/null || true

# Submit new job
echo "Submitting PyTorchJob..."
kubectl apply -f kubeflow_test_job.yaml

echo "Job submitted."
echo "You can check status with:"
echo "  kubectl get pytorchjobs"
echo "  kubectl get pods"
echo "  kubectl logs -l pytorch-job-name=pytorch-dist-test -f"
